name: Python CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests with pytest and measure coverage
      run: |
        coverage run -m pytest  # Lance pytest avec coverage
        coverage report        # Affiche un résumé de la couverture
        coverage html          # Génère un rapport de couverture HTML
        coverage report --fail-under=60  # Échoue si la couverture est < 60%

